steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '--build-arg', 'VUE_APP_API_SERVER=https://api.pixvie.tech', '--build-arg', 'VUE_APP_SOCKET_SERVER=https://api.pixvie.tech', '-t', 'eu.gcr.io/$PROJECT_ID/pixvie-fe', '.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'eu.gcr.io/$PROJECT_ID/pixvie-fe']
- name: "gcr.io/cloud-builders/git"
  args: ['clone', 'https://github.com/Pixvie/pixvie-k8s-infra.git']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --filename=service.yaml
  - --location=europe-west3
  - --image=eu.gcr.io/$PROJECT_ID/pixvie-fe
  - --cluster=emrullah-cluster-1
  dir: "pixvie-k8s-infra/apps/pixvie-fe"
