apiVersion: apps/v1
kind: Deployment
metadata:
    name: pixvie-fe-deployment
    labels:
        app: pixvie-fe
spec:
    replicas: 2
    selector:
        matchLabels:
            app: pixvie-fe
    template:
        metadata:
            labels:
                app: pixvie-fe
        spec:
            containers:
                - name: pixvie-fe
                  image: emrullahcirit/pixvie-fe:latest
                  ports:
                      - containerPort: 80
