apiVersion: apps/v1
kind: Deployment
metadata:
    name: pixvie-fe-deployment
    labels:
        app: pixvie-fe
spec:
    replicas: 2
    selector:
        matchLabels:
            app: pixvie-fe
    template:
        metadata:
            labels:
                app: pixvie-fe
        spec:
            containers:
                - name: pixvie-fe
                  image: emrullahcirit/pixvie-fe:latest
                  ports:
                      - containerPort: 80
                  env: 
                  - name: VUE_APP_API_SERVER
                    value: http://35.198.166.105:3000
                  - name: VUE_APP_SOCKET_SERVER 
                    value: http://35.198.166.105:3000/socket
